# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, editable=False, max_length=5, verbose_name='language')),
                ('field_name', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='field name')),
                ('weight', models.IntegerField(db_index=True, default=0, verbose_name='Weight')),
                ('data', models.FloatField(blank=True, null=True, verbose_name='Float')),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scms.Page', verbose_name='page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
