# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0002_float_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='float',
            name='sites',
        ),
    ]
