# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_colorplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=5, verbose_name='Language'),
        ),
    ]
