# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_auto_20160803_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='measure',
            field=models.CharField(blank=True, default=b'', max_length=256, verbose_name=b'\xd0\x98\xd0\xb7\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
