# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0010_auto_20160831_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='weight',
            field=models.IntegerField(db_index=True, verbose_name=b'\xd0\x92\xd0\xb5\xd1\x81'),
        ),
    ]
