# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(db_index=True, max_length=64, verbose_name=b'\xd0\xa1\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe \xd0\xb2 \xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbb\xd0\xb8\xd1\x82\xd0\xb8\xd1\x80\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name=b'\xd0\xa0\xd0\xb0\xd0\xb7\xd0\xbc\xd0\xb5\xd1\x80')),
                ('weight', models.IntegerField(db_index=True, max_length=256, verbose_name=b'\xd0\x92\xd0\xb5\xd1\x81')),
            ],
            options={
                'ordering': ['weight', 'vocabulary', 'name'],
                'verbose_name': '\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440',
                'verbose_name_plural': '\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, editable=False, max_length=5, verbose_name='language')),
                ('field_name', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='field name')),
                ('weight', models.IntegerField(db_index=True, default=0, verbose_name='Weight')),
                ('value', models.CharField(db_index=True, max_length=256, verbose_name=b'\xd0\x97\xd0\xbd\xd0\xb0\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scms.Page', verbose_name='page')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='parameters.Parameter', verbose_name=b'\xd0\x9f\xd0\xb0\xd1\x80\xd0\xb0\xd0\xbc\xd0\xb5\xd1\x82\xd1\x80')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
