# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import scms.plugins.parameters.models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x86\xd0\xb2\xd0\xb5\xd1\x82\xd0\xb0')),
                ('html', scms.plugins.parameters.models.ColorField(max_length=10, null=True, verbose_name=b'HTML-\xd0\xbf\xd1\x80\xd0\xb5\xd0\xb4\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u0426\u0432\u0435\u0442',
                'verbose_name_plural': '\u0426\u0432\u0435\u0442\u0430',
            },
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
