# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_parameter_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorPlugin',
            new_name='Colors',
        ),
    ]
