# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_auto_20160831_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='sites',
        ),
    ]
